src/components/ActivitiesItemAssessment.vue, src/components/ActivitiesItemResult.vue, src/components/ActivitiesTable.vue, src/components/ActivityInput.vue, src/components/NavHeader.vue, src/components/mixins/customValidation.js, src/components/mixins/dataIO.js, src/locales/en.yaml, src/router.js, src/views/Assessment.vue, src/views/BestPractice.vue, src/views/BestPractices.vue
=> Translation strings

project_todo.todo, src/components/ActivityInput.vue, src/components/BaseFlyout.vue, src/components/BaseFormInput.vue, src/components/NavHeader.vue, src/components/NavTimeline.vue, src/locales/en.yaml, src/stylesheets/config/_spacing.scss, src/views/Setup.vue
Laid out activity nav, got it mostly working.
=> Activity nav

project_todo.todo, src/components/ActivitiesItemResult.vue, src/components/ActivityRecommendationInput.vue, src/components/BaseFormInput.vue, src/components/BaseFormLabel.vue
branch name is a lie. I quickly touched up the suggestion inputs, figured I'd push this separately in case I don't finish the chart layouts before 3.
=> layout for recommendtion input

project_todo.todo, src/components/ChartItems.vue, src/components/ChartPie.vue, src/locales/en.yaml
Quick first pass on chart layout styling. Needs significant refactoring but it's at a point where it's more readable.
=> Chart layouts

project_todo.todo
Added stuff from our notes from the review today. Please add anything I might have missed, or that you'd like to cover.
=> add todos from prototype review today

src/locales/en.yaml, src/locales/fr.yaml
Pull request created by LingoHub based on branch master
=> LingoHub based on master

src/locales/en.yaml
@jayperryworks @sschafft could you give this a quick review and let me know if i've missed any? then i'll address these on LingoHub. thanks!
=> initial 'Do Not Translate' additions

src/locales/en.yaml
- Adjusted indentations to match YAML syntax
- Added missing markdown bold asterisks
- Adjusted quotation marks
=> Commit reviews

src/locales/en.yaml
- Resolved some markdown errors that were displaying best practice text incorrectly
=> fix bullet issues

src/locales/en.yaml
- edited footnote error
- fixed line spacing by adding `\` syntax
- removed lone lorem ipsum
=> Footnotes and spacing

src/authorities/currency-data.json
- removed duplicates and outdates currencies
- all currencies should be listed and in alphabetical order
=> add in missing country codes, alphabatize

src/components/ActivitiesItemResultPrint.vue, src/components/ActivitiesListHeader.vue, src/components/ChartItems.vue, src/components/mixins/bestPracticeData.js, src/views/Print.vue, src/views/Results.vue
Issues: 
- [#56]
- [#57]
Fixes:
- rendering errors on the print page causing browser lockup
- pie graphs showing totals greater than 100
=> Print page

src/components/ActivitiesItemAssessment.vue, src/components/ActivitiesItemResult.vue, src/components/ActivitiesListHeader.vue, src/components/ActivitiesTypeHeading.vue, src/components/ActivityInput.vue, src/components/ChartItems.vue, src/components/mixins/bestPracticeData.js, src/components/mixins/dataMethods.js, src/locales/en.yaml, src/locales/fr.yaml
Issues:
- Resolves [#58]
- Resolves [#60]
=> Debug activities and charts

src/components/ActivityRecommendationInput.vue, src/components/GlobalRecommendation.vue, src/locales/en.yaml, src/models/GlobalRecommendation.js, src/store/database.js, src/store/modules/globalrecommendations.js, src/views/Advocate.vue, src/views/Print.vue
Initial stab at global recommendations. 
- Added input to the advocate page
- Added text to the print page
Initial work on #79
=> Overall recommendations

src/components/ActivitiesExportTray.vue, src/components/FileExport.vue, src/components/NavFooter.vue, src/components/NavHeader.vue, src/locales/en.yaml, src/router.js, src/views/Advocate.vue, src/views/Export.vue, src/views/Setup.vue
PR to support save data reminders.
Resolves #81 
Save on all pages except Results & Advocate
Export on Results & Advocate
=> Save workflow

package.json, project_todo.todo, src/components/ActivitiesExportTray.vue, src/components/FileExport.vue, src/components/NavFooter.vue, src/components/NavHeader.vue, src/locales/en.yaml, src/main.js, src/router.js, src/views/Advocate.vue, src/views/Export.vue, src/views/Setup.vue, yarn.lock
=> Google analytics

package.json, project_todo.todo, src/components/ActivitiesExportTray.vue, src/components/FileExport.vue, src/components/NavFooter.vue, src/components/NavHeader.vue, src/locales/en.yaml, src/main.js, src/router.js, src/views/Advocate.vue, src/views/Export.vue, src/views/Home.vue, src/views/Setup.vue, yarn.lock
=> Acknowledgements

project_todo.todo, src/App.vue, src/components/NavFooter.vue, src/locales/en.yaml, src/locales/fr.yaml, src/views/Setup.vue
Update french and electron export links
=> Update french and electron

src/components/NavBreadcrumbs.vue, src/components/NavHeader.vue, src/components/NavItem.vue, src/store/index.js, src/views/Activity.vue, src/views/BestPractices.vue, src/views/Plan.vue, src/views/Results.vue
In order to incrementally indicate the progress of sub steps in the
NavBreadcrumbs component, this commit refactors the application to use
global state to set the progress of the user through the app. This
allows us to indicate easily how far they have progress through the app.
This commit also indicates which sub step the user is on and partially
fills the progress bar accordingly.
=> Refactor NavBreadcrumbs to use global state

src/components/BestPracticeIconSelect.vue, src/locales/en.yaml, src/locales/fr.yaml, src/views/Plan.vue
This commit applies some misc copy and layout edits based on feeback.
=> Misc copy and layout edits

src/components/NavHeader.vue
This commit fixes an issue where the logo and the logo text were not
aligning correctly vertically.
=> Fix logo alignment

src/locales/en.yaml, src/locales/fr.yaml
This commit fixes a few copy issues.
=> Couple copy issues

src/background.js, src/components/ActivitiesItemAssessment.vue, src/components/ActivitiesItemInput.vue, src/components/ActivityTray.vue, src/components/PrintPage.vue, src/locales/fr.yaml
This commit fixes the spacing of a few buttons between translations and
updates the copy a bit.
=> Fix button spacing and copy

src/components/ActivitiesItemInput.vue, src/components/BaseFormInput.vue
This commit fixes an issue where the texteara input wwould type in
reverse in Edge
=> Fix ie textarea bug

src/components/CountryIndicator.vue, src/components/ResultsCharts.vue, src/views/Print.vue
This commit refactors the country indicator component so that we can
toggle the questions to consider.
=> Remove questions to consider from print

src/locales/fr.yaml
This commit makes a few minor copy punctuation edits
=> Minor copy edits

src/locales/fr.yaml
This commit fixes an issue with the french translation url, where we
did not update the offline url
=> Update french translation download url

src/components/ActivityInput.vue, src/components/BaseFormSwitch.vue, src/components/mixins/activityTypes.js, src/views/Activity.vue, src/views/Assessment.vue
This commit fixes an issue with the checkbox for the youth centric
definition. Essentially, the checkbox was not bound correctly to the youth
centric value, and while the bug was over looked in Chrome, Edge did not
like it. This prevented any activities from being marked as youth centric,
and thus showing up in the activity tray.
=> Fix checkbox issue
