src/components/ChartItems.vue
- corrected `getRoundedPercentages()` function to restore the number order of the original array, so that the correct numbers are passed to each legend item
- fixed some bugs in the original sort()
- cleaned up and added explanatory comments
=> Rounded percentages refactor

src/components/BaseStepList.vue, src/components/BaseVerticalList.vue, src/locales/en.yaml, src/locales/fr.yaml, src/views/Advocate.vue, src/views/Home.vue, src/views/Print.vue
- Add a 4th step to the homepage and modify the `BaseStepList` component so the column number can be config'd with props
- clean up styles/layout on global recommendations
- Resolves #82
- Resolves #79
=> New steps & recommendation styles

src/locales/en.yaml
- put double quotes around key values with ":" in the resource title
- fixed indentation of resources that was causing errors
=> Fix indentation and quotation issues in en.yaml file

src/components/ActivityInput.vue, src/components/BestPracticeInfoIcon.vue, src/locales/en.yaml, src/views/Activity.vue
This commit simplifies the activity saving process. When an activity is
input, the user will need to press the save button to submit a new
activity. This will clear the form and take the user to the top of the
form. If the users is editing an activity, the activity will be saved
with each input change. In order to avoid confusion, the save activity
button is still present in the edit view. From the edit activity view,
the user also has the option to add another activity or save the current
activity.
=> Simplify activity saving

src/views/Advocate.vue
This commit adds the Go Back buttons to the print and advocate routes.
The button will use the browser history state to return to the previous
page. If not history is present, it will go back to the `/results`
route.
=> Add Go Back button to print/advocate routes

src/components/ActivityTray.vue, src/components/BaseBodyText.vue
This commit fixes an issue where we were using the `text` value from the
activity in the activity tray as the title. This resulted in an
unreadable layout. This commit modifies the activity tray to use the
`activityNumber` as the title, and to display the `text` in the body.
**Before**
**After**
=> Use `activityNumber` as title in activity tray

src/components/ActivitiesItemInput.vue, src/components/BaseBodyText.vue, src/components/GlobalRecommendation.vue
This commit fixes an issue with the add key recommendations section,
where recommendations would not be displayed at all when added. This
commit updates the section to add an editable recommendation after
clicking the "Add Another Recommendation" button.
=> Fix submit recommendations issue

src/components/ClearItems.vue
This commit fixes an issue where the clear all button did not also clear
the apps nav breadcrumb progress.
=> Clear progress issue

src/components/ActivitiesItemAssessment.vue, src/views/Print.vue, src/views/Results.vue
This commit ensures that the global recommendations are visible in the
print view, and ensures that the ActivityNumber is used instead of the
Activity Text as the header on the results page EIP table.
=> Clean up Print view

src/locales/en.yaml
Because the enhanced toggle checkbox is not available in IE, this commit
updates the fallback support copy to make more sense when the user is
presented with just a checkbox.
=> Update Youth Centric copy

src/components/ActivitiesItemInput.vue
This commit ensures that the width of the recommendation input is 100%
on ie devices.
=> Fix add recommendation input width

src/components/NavFooter.vue
This commit fixes an issue with button stacking in the nav footer when
we have buttons with a lot of text. This commit splits the nav 40/60
instead of 50/50. With the right side having more screen real estate.
This prevents the right buttons from stacking in french translations.
=> Fix button stacking in footer

src/components/ActivitiesItemInput.vue, src/components/PrintPage.vue, src/components/mixins/electronPDF.js
This commit fixes the pdf export process so the user does not see a
white blank screen after saving the pdf. This commit also adds a misc
fix for the recommendation input textarea width.
=> Fix the export

src/components/ActivitiesItemAssessment.vue, src/components/NavItem.vue
This commit ensures that the EIP icons are always visible, regardless of
whether or not the activity is youth centric. It also tweaks the
progress bar a bit, having specific styles if the nav item is the
furthest progress item in the application.
=> Always show EIP icons

src/components/CountryIndicator.vue, src/components/NavItem.vue, src/components/mixins/dataMethods.js, src/locales/en.yaml, src/locales/fr.yaml
This commit adds a fall back text for CountryIndicators in the Results
view. This text indicates that the data does not exist for the given
indicator and country pair.
=> Add fallback text for CountryIndicators

src/components/ChartItems.vue, src/components/ChartLegend.vue, src/components/mixins/dataMethods.js
This commit fixes an error with the budget chart labels. Specifically,
it addresses an issue where if there are no youth centric activities,
the budget will show 25% be allotted to each category, even though it
should read 0%.
=> Fix percentage error

src/components/NavHeader.vue, src/components/PrintPage.vue, src/views/Home.vue
To avoid confusion with users, this commit prevents any new windows from
being opened in the electron app.
=> Prevent pdf from opening in new window

src/components/ActivitiesItemAssessment.vue, src/views/Print.vue, src/views/Results.vue
This commit fixes an issue where the activity number was not being
displayed in the results or print view
=> Display activity number in print

src/components/ActivityInput.vue, src/components/NavFooter.vue, src/locales/en.yaml, src/main.js, src/views/Activity.vue
This commit refactors the activity saving workflow. This commit
introduces a global emitter bus that allows us to trigger an event in
one component, and listen to it in another component, regardless of
their relationship. This is used in the `NavFooter` to call an action
that triggers an event/method in the `ActivityInput` component.
This commit configures the `NavFooter` to save the Activity instead of
the `ActivityInput` component.
=> Refactor save

src/components/mixins/electronPDF.js
In order to overwrite the saved pdf, but still maintain a
timestamp/version of the saved pdf, this commit updates the timestamp
used. Instead of using a unix timestamp as the pdf suffix, this commit
uses the dd-mm-yyyy format as the suffix. This will allow users to
overwrite pdfs on the same day, while working, and also maintain a
version history when working over several days.
=> Update pdf timestamp

src/components/ActivityInput.vue, src/components/mixins/activityBudget.js, src/locales/en.yaml, src/locales/fr.yaml
This commit updates the population prospect data source url to reflect
the new 2019 data. While the data itself was up to date, all of the
sources citing the data linked to the incorrect spreadsheet.
This commit also removes the activity budget scale field, as it was
causing a good deal of confusion. Instead, we are using a locale
specific budget field for formatting budget inputs using the correct
locale.
=> Update population prospects data and remove activity budget scale

src/components/ActivitiesList.vue, src/components/ActivitiesListHeader.vue, src/components/BaseFormSwitch.vue, src/components/TableHeading.vue
This commit fixes the header of the activites tray, ensuring that flex box
styles are applied on ie11 browsers. It also fixes an issue with the
checkbox on chrome, where the value was not being updated correctly.
=> Fix ie11 styles for activites tray
